LABEL velvet
  LINUX /Image-KERNEL_VERSION
  INITRD /initrd.img-KERNEL_VERSION
  FDT /dtb-KERNEL_VERSION/rk3566-powkiddy-x55.dtb
  #there are levels from 1 to 3 + no overlay
  #each should give more battery life but might cause issues
  #please be careful
  #FDTOVERLAYS /rk3566-undervolt-cpu-l3.dtbo
  APPEND console=ttyS2,1500000n8 console=tty1 no_console_suspend consoleblank=0 root=LABEL=rootpart rootwait ro fsck.fix=yes fsck.repair=yes net.ifnames=0 noresume apparmor=0
