LABEL velvet
  LINUX /Image-KERNEL_VERSION
  INITRD /initrd.img-KERNEL_VERSION
  FDT /dtb-KERNEL_VERSION/rk3399-anbernic-rg552.dtb
  APPEND console=ttyS2,1500000n8 console=tty1 no_console_suspend consoleblank=0 root=LABEL=rootpart rootwait ro fsck.fix=yes fsck.repair=yes net.ifnames=0 noresume apparmor=0
